databases:
  - name: fake_cphc
    databaseName: fake_cphc
    user: fake_cphc

services:
  - type: web
    name: fake_cphc
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fake_cphc
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
